package demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Gameover implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String outcome;

   public Gameover()
   {
   }

   public java.lang.String getOutcome()
   {
      return this.outcome;
   }

   public void setOutcome(java.lang.String outcome)
   {
      this.outcome = outcome;
   }

   public Gameover(java.lang.String outcome)
   {
      this.outcome = outcome;
   }

}
