package demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Move implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String player;
   private int position;

   private int value;

   private int value2;

   public Move()
   {
   }

   public java.lang.String getPlayer()
   {
      return this.player;
   }

   public void setPlayer(java.lang.String player)
   {
      this.player = player;
   }

   public int getPosition()
   {
      return this.position;
   }

   public void setPosition(int position)
   {
      this.position = position;
   }

   public int getValue()
   {
      return this.value;
   }

   public void setValue(int value)
   {
      this.value = value;
   }

   public int getValue2()
   {
      return this.value2;
   }

   public void setValue2(int value2)
   {
      this.value2 = value2;
   }

   public Move(java.lang.String player, int position, int value, int value2)
   {
      this.player = player;
      this.position = position;
      this.value = value;
      this.value2 = value2;
   }

}
