package demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Playermove implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int position;

   public Playermove()
   {
   }

   public int getPosition()
   {
      return this.position;
   }

   public void setPosition(int position)
   {
      this.position = position;
   }

   public Playermove(int position)
   {
      this.position = position;
   }

}
